### ISSUE TITLE
Usage with `nom`

### ISSUE THREAD

**Issue by LoganDark** [BurntSushi/bstr#103]
It would be nice if `bstr` had an optional `nom` feature that implemented `nom` traits like `Slice`, `InputTakeAtPosition`, etc.

As-is, it's difficult to use `BStr` in `nom` parsers due to the lack of any traits.

**Comment by BurntSushi** [comment]
I don't see myself adding a dependency on a specific parser framework. Sorry.

You'll have to either use byte slices directly (which BStr derefs too) or create your own wrapper type around BStr.

**Comment by LoganDark** [comment]
I was more proposing something similar to what you already have with `serde`, where the dependency is *optional* and *not enabled by default*. If you have something against `nom`, though, I won't pressure you. (Sorry for the issue.)

**Comment by BurntSushi** [comment]
You don't have to apologize for the issue. It's okay to ask. And I assumed you were asking for an optional dependency.

To be clear, I don't have anything against nom. Serde is a foundational library. nom is not. You must realize that I have to have some kind of threshold for these sorts of requests, otherwise I'm liable to have a whole litany of optional dependencies with trait impls. It just isn't reasonable. Serde might be the only crate that meets my threshold.
