### ISSUE TITLE
Character-oriented slicing and length APIs

### ISSUE THREAD

**Issue by lopopolo** [BurntSushi/bstr#118]
I have three APIs that I've implemented as a downstream user of `bstr` that I'd be interested in upstreaming if there is appetite:

```rust
trait ByteSlice {
    /// Returns a byte slice containing the byte sequence for the index-th character in self.
    ///
    /// Each byte in an invalid UTF-8 byte sequence is counted as one character.
    pub fn get_char(&self, index: usize) -> Option<&'_ [u8]>;
    /// Returns a byte slice containing the byte sequences for characters between the
    /// indexes specified by the range in self.
    ///
    /// Each byte in an invalid UTF-8 byte sequence is counted as one character.
    pub fn get_char_slice(&self, range: Range<usize>) -> Option<&'_ [u8]>;
    /// Returns a number of conventionally UTF-8 characters in self.
    ///
    /// Each byte in an invalid UTF-8 byte sequence is counted as one character.
    pub fn char_len(&self) -> usize;
}
```

Each of these APIs is able to be implemented with the `CharIndicies` iterator, but with dedicated signatures we can perform significantly better than doing a single UTF-8 decode at a time (for example with fast paths for ASCII).

If you're interested in these APIs and want to take a peek at the implementations I have, see below. For the examples, the `utf8` variants are the relevant ones.

## `char_len`

code: https://github.com/artichoke/artichoke/blob/f32107a7c170c2e7440ba1966ccb67e4452add81/spinoso-string/src/enc/utf8/mod.rs#L139-L162
docs + examples: https://artichoke.github.io/artichoke/spinoso_string/struct.String.html#method.char_len

## `get_char`

code: https://github.com/artichoke/artichoke/blob/f32107a7c170c2e7440ba1966ccb67e4452add81/spinoso-string/src/enc/utf8/mod.rs#L209-L284
docs + examples: https://artichoke.github.io/artichoke/spinoso_string/struct.String.html#method.get_char

## `get_char_slice`

code: https://github.com/artichoke/artichoke/blob/f32107a7c170c2e7440ba1966ccb67e4452add81/spinoso-string/src/enc/utf8/mod.rs#L286-L454
docs + examples: https://artichoke.github.io/artichoke/spinoso_string/struct.String.html#method.get_char_slice

**Comment by BurntSushi** [comment]
Yeah hmm unfortunately there are two issues I can see with these APIs.

The first is philosophical. That is, APIs for indexing by codepoint are generally not something I want to encourage, because it's _almost_ always not what you want. I know that the use cases for them aren't zero, but it's pretty close to zero, to the point where I wouldn't want to encourage folks to use them when they shouldn't and don't mind if people who need them implement them themselves.

The second is more specific to how you've described they should work and how you've implemented them. In particular, the docs you've provided note that they treat each invalid UTF-8 byte as a single character. It's not quite fully precise, so I went and checked how you implemented them, and indeed, you also [count each byte that is part of a prefix of a valid UTF-8 sequence](https://github.com/artichoke/artichoke/blob/f32107a7c170c2e7440ba1966ccb67e4452add81/spinoso-string/src/enc/utf8/mod.rs#L159) as a distinct character. That's not wrong, but it is inconsistent with how the [rest of the bstr crate works](https://docs.rs/bstr/latest/bstr/#handling-of-invalid-utf-8).
