### ISSUE TITLE
Possible panic safety issues in insert_str

### ISSUE THREAD

**Issue by kitcatier** [BurntSushi/bstr#153]
Hi,  We noticed a potential issue in the provided  insert_str. During this part, the elements are shifted over which can potentially duplicate them. After this, In case of a panic, the duplicated elements can be dropped twice leading to a double free.
https://github.com/BurntSushi/bstr/blob/65993b58be1547bfc0de9ad8c1c8f3d3fcb0a32f/src/ext_vec.rs#L806-L836

**Comment by BurntSushi** [comment]
The critical part of your issue here is "in case of panic." Where does that panic occur? And what exactly is being double freed?

You might be right if this were a data structure like `Vec` that can hold some arbitrary `T` which might not be `Copy` and might have custom destructors and what not defined. But that is not the context in which this code is executing. It is only limited to dealing with `u8` elements. The `SAFETY` comment even mentions this:

https://github.com/BurntSushi/bstr/blob/65993b58be1547bfc0de9ad8c1c8f3d3fcb0a32f/src/ext_vec.rs#L811-L814

Now I could be wrong, but at the very least, the possibility with which you speak is certainly something I considered when writing this code. So I'm going to need more to go on here. The gold standard would be an executable program that I can run under Miri that reports a problem that isn't a false positive.

**Comment by kitcatier** [comment]
> 

That's right, I see, thanks
