### ISSUE TITLE
Adding license info

### ISSUE THREAD

**Issue by erickt** [BurntSushi/bstr#30]
Hello @BurntSushi! Would it be possible to add some more license info?

* In src/unicode, it appears that you've extracted some data from unicode.
* In src/utf8.rs, you mention that code is based off of https://bjoern.hoehrmann.de/utf-8/decoder/dfa/, but don't reference what license that code falls under.

Could you add these licenses to the crate, and reference this in the Cargo.toml / readme? Thanks so much!

**Comment by BurntSushi** [comment]
@erickt The Unicode data is only used in tests. Otherwise, all Unicode data comes in form of finite state machines generated by `ucd-generate`. Regardless, I've added a note about this in the README.

As for src/utf8.rs, I feel that the comment there is enough. I do not agree that the copyright of src/utf8.rs falls under the copyright of https://bjoern.hoehrmann.de/utf-8/decoder/dfa/.
