### ISSUE TITLE
Should CLASSES and STATES_FORWARD be const?

### ISSUE THREAD

**Issue by FlyingCanoe** [BurntSushi/bstr#47]
The decoding process seam to relies on those tow array. It don't seam like they get mutated anywhere, so in that context should they be const instead of static? I have tested and it do not appear like this modification break anything.

Also it seam that decode unsafe block rely on the decode_step logic to be correct. In this case should a comment be add a the top of decode_step to warn that faulty logic in that function would result in UB?

And again, bean pretty new to programming and to rust I may not know what are the best practice for those tow case and I may have miss something.

**Comment by BurntSushi** [comment]
> It don't seam like they get mutated anywhere, so in that context should they be const instead of static?

Seems reasonable. You can't mutate a `static` anyway. You need `static mut` for that. A PR is welcome, otherwise I'll tweak it next time I'm in that file.

> Also it seam that decode unsafe block rely on the decode_step logic to be correct. In this case should a comment be add a the top of decode_step to warn that faulty logic in that function would result in UB?

Maybe? It should also be on the state machine itself then too. I tend to think the comments on the `unsafe` blocks are sufficient in this regard. There is kind of always a fundamental assumption in `unsafe` code that the other code you're relying on is _correct_. The main caveat to this is when that "other code" is generic of some kind. In that case, your `unsafe` code cannot let UB happen no _matter what_ the behavior the generic is (unless you some how expose `unsafe` in your API somewhere). But that's not the case here: it's just relying on other concrete code in the same module to do what it says it does.

With that said, I'm always in favor of improving docs, especially around safety. So a PR is welcome.

Thanks for the issue! It's good insight.
