### ISSUE TITLE
More compatible escapes for control characters

### ISSUE THREAD

**Issue by tailhook** [BurntSushi/bstr#56]
Current `Debug` implementation yields something like this:
```
"\u{0}\u{0}\u{0} ftypisom\u{0}\u{0}\u{2}\u{0}isomiso2avc1mp"
```
And I'd like it to be like this:
```
"\0\0\0 ftypisom\0\0\x02\0isomiso2avc1mp"
```
***Edit:** these are first bytes of mp4 file, so quite real-world example*
This is not only compatible with Rust (even for str constants), but also with C, Python, Bash, and probably more languages. And also a bit shorter.

1. What do you think of changing the representation?
2. If changing is okay, what to do with non-printable chars > 0xff? There is two choices: keep them as current `\u{..}` or always escape with `\x`. I would prefer latter, because when working with binary data looking at individual bytes makes more sense, and when working with textual data, these character codes are rarely informing enough.

**Comment by BurntSushi** [comment]
I'm not a huge fan of `\u{0}` either to be honest, but I also would prefer `\x00` instead of an octal escape. Using hex escapes would be consistent with using hex escapes for invalid UTF-8.

For non-printable Unicode scalar values, I'd prefer the `\u{...}` syntax, since that to me seems like it provides the most signal. I think that's probably why we get `\u{0}` instead of `\x00`, because `U+0000` is a non-printable Unicode scalar value. So using `\x00` instead of `\u{0}` is a bit inconsistent.

I'm also not a huge fan of diverting from `std` on this, since the implementation just defers to [`char::escape_debug`](https://doc.rust-lang.org/std/primitive.char.html#method.escape_debug) at the moment. But maybe a better set of rules would be:

* If invalid UTF-8, use `\xZZ`.
* If non-printable ASCII, use `\xZZ`.
* Otherwise, defer to `char::escape_debug`.
