### ISSUE TITLE
A helper macro for bytestring concatenation/formatting

### ISSUE THREAD

**Issue by Alphare** [BurntSushi/bstr#57]
Hi there,

I've just released an article about bytestrings and encoding in general here: https://www.reddit.com/r/rust/comments/gz33u6/not_everything_is_utf8/, at the end of which I mention my intention of creating a `format_bytes!` macro to... format bytes.

I was wondering whether you had built that functionality somewhere I could re-use, or - if not - if you think that it would be a good fit for the `bstr` crate baring maybe a cargo feature for the added compilation dependencies for proc macros.

(Copy-pasted from an earlier exchange to preserve its history)

**Comment by BurntSushi** [comment]
And copying my response. :-)

I'm open to the idea. But I definitely have concerns:

* How well motivated is it? Can you provide some compelling examples
for using it?

* Macro dependencies, as you mention. I'd probably want to therefore
disable it by default, since proc macros increase compile times and
bloat the dependency tree.

* The implementation complexity of `format_bytes!`. AIUI, the
implementation in std is considerably complex, and I'm not sure I'm
comfortable inheriting the maintenance burden for something like that.
So in that sense, `format_bytes!` might be better as its own crate. If
we decided to go that route, then I'd be happy to link to it from
bstr's README.

**Comment by Alphare** [comment]
I've updated my article to mention the example of `hg log --patch` that will contain internal strings in local encoding to mark fields, UTF-8 metadata, and file contents in an unknown encoding. 

A simpler example would be the following: 

```python
msg = _(b"%s: ignoring invalid syntax '%s'\n") % (file_path, syntax)
```
This is in Python code related to `.hgignore` handling, the Rust equivalent could be (not accounting for i18n call):

```rust
let msg = format_bytes!(b"{}: ignoring invalid syntax '{}'\n", &file_path, &syntax);
```
> AIUI, the implementation in std is considerably complex

I couldn't find the actual implementation, it seems to be a compiler intrinsic, but I think `format_bytes` will be less complex since a lot of formatting options won't make sense and it would be more of a "concatenation helper" than anything.

However I think I'm inclined to go the separate crate route, thinking about it. It's simpler from a dependency/features standpoint and I'm not dumping more maintenance burden on you.

Maybe you can humor some bikeshedding: do you think `format_bytes` is an appropriate name taking my answer into account?

**Comment by BurntSushi** [comment]
I think `format_bytes!` is a good name. If it were in `bstr` proper, then I might consider naming it just `format!`, so that you could (presumably) use it as `bstr::format!`. So if you find a good crate name, you might be able to do the same.

Starting in a separate crate sounds good. If the implementation winds up being much simpler than I think, then maybe we can compare notes at that point and consider whether to just bring it into `bstr`.

**Comment by BurntSushi** [comment]
I'm going to close this out since I don't have any current plans to pursue or adopt this. I think the thing scaring me away from this is the implementation complexity. I think it would be biting off more than I can chew.

However, I'm happy to be shown that this can be simpler than I think, in which case, I would consider merging it into bstr.
