### ISSUE TITLE
Add more From impls for constructing Cow

### ISSUE THREAD

**Issue by lopopolo** [BurntSushi/bstr#59]
I'm constructing a set of error messages that use `Cow<'static, [u8]>` because the vast majority of messages are static byte strings, but some require dynamic allocation (for example by deferring to the `Display` impl of a wrapped error). The actual message field is a `Cow<'static, BStr>` to make use of `BStr`'s debug implementation.

The constructors for the error structs are all `From` impls on owned and borrowed `String` and `Vec<u8>`.

Trying to construct a `Cow<'_, Bstr>` from a `Vec<u8>` or `&'a [u8]` is a bit verbose because the compiler gets confused when you `buf.into().into()`. I end up having to write:

```rust
impl From<Vec<u8>> for Message {
    fn from(message: Vec<u8>) -> Self {
        Self(Cow::Owned(message.into()))
    }
}

impl From<&'static [u8]> for Message {
    fn from(message: &'static [u8]) -> Self {
        Self(Cow::Borrowed(message.into()))
    }
}
```
Can we add a direct set of impls for constructing a `Cow`?

```rust
impl<'a> From<Vec<u8>> for Cow<'a, BStr> {
    fn from(bytes: Vec<u8>) -> Self {
        Cow::Owned(bytes.into())
    }
}
impl<'a> From<&'a [u8]> for Cow<'a, BStr> {
    fn from(bytes: &'a [u8]) -> Self {
        Cow::Borrowed(bytes.into())
    }
}
```

And maybe `impl<'a> From<Cow<'a, [u8]>> for Cow<'a, BStr>`.

These impls would also make it easier to turn a `String`/`&str` Cow into a `BStr` Cow.

**Comment by BurntSushi** [comment]
Unfortunately, no, none of those impls are allowed because of coherence (I just checked). For example, in the case of `From<Vec<u8>> for Cow<'a, BStr>`, neither `Vec<u8>` nor `Cow` are defined in `BStr`, which means the impl isn't allowed.

There are _a lot_ of impls in `src/impls.rs`.  If you find a missing impl that is legal, then please feel free to just submit a PR. :-) Thanks.
