### ISSUE TITLE
Q: Perf difference when using bstr vs regular Strings

### ISSUE THREAD

**Issue by v1gnesh** [BurntSushi/bstr#90]
Hi,

Will there be any performance difference when using `bstr` (i.e., without the UTF8 validation) compared to regular Rust `String`s?

If so, is it noticeable enough that if my program is parsing out hundreds of strings from binary data (which itself will be in gigs), I can instead opt for bstr?

Thanks in advance for your answers

**Comment by BurntSushi** [comment]
In one case, you are doing work to validate UTF-8, which requires visiting the entire string. In another case, you are doing no work. So, which do you think is faster? :-)

Whether it is noticeable or not depends on your work load. You need to write your own benchmarks.

Performance is not the only reason to use `bstr`. You might also want to use it when your strings might only be conventionally UTF-8, but are not necessarily guaranteed to be UTF-8. This is pretty common in practice since it's rare for a file to declare what its encoding is.
